### ISSUE TITLE
Example on how to use Bound.Name

### ISSUE THREAD

**Issue by sgraf812** [ekmett/bound#35]
I think I figured out how `Bound.Name` works, but am unsure which parts of the AST should be decorated with it. The other functions in the module suggest to decorate the first parameter of `Scope`, but it's weird not to have access to the name when matching on `Lam`. 

Could you drop a really short example? Just the modified basic `Exp` type + the `Lam` case of a pretty printing function like [here](https://github.com/ekmett/bound/blob/master/examples/Simple.hs#L187-L188) which figures out the right name for the bound variable should be enough.

**Comment by sgraf812** [comment]
I went with the other variant: `Lam (Name Text ()) (Scope () Exp a)`, which also feels a little strange, but will probably do the job.

**Comment by Ptival** [comment]
So it seems that the two choices are kinda weird:

- if you do:
```
Lam (Name a ()) (Scope () Exp a)
```
Then, you can't write a `Monad` instance for `Exp`, because you have no way to turn this `Name a ()` into a `Name b ()` given only an `a -> Exp b`

- but if you do:
```
Lam (Name String ()) (Scope () Exp a)
```
Then any function that abstracts over a variable (while trying to retain a name) will have to be monomorphized to `String`, since the type of `abstract1Name` forces it.

Maybe the latter is okay though: it seems the idea is, the type variable is polymorphic to get guarantees for binder-agnostic functions, but in practice it will be `String`.
